market_split_u3_01 = ["models/market-split/market_split_u3_01.fzn", "models/market-split/market_split_u3_01.scaffold.drcp"]
market_split_u3_02 = ["models/market-split/market_split_u3_02.fzn", "models/market-split/market_split_u3_02.scaffold.drcp"]
market_split_u3_03 = ["models/market-split/market_split_u3_03.fzn", "models/market-split/market_split_u3_03.scaffold.drcp"]
market_split_u3_04 = ["models/market-split/market_split_u3_04.fzn", "models/market-split/market_split_u3_04.scaffold.drcp"]
market_split_u3_05 = ["models/market-split/market_split_u3_05.fzn", "models/market-split/market_split_u3_05.scaffold.drcp"]
market_split_u3_06 = ["models/market-split/market_split_u3_06.fzn", "models/market-split/market_split_u3_06.scaffold.drcp"]
market_split_u3_07 = ["models/market-split/market_split_u3_07.fzn", "models/market-split/market_split_u3_07.scaffold.drcp"]
market_split_u3_08 = ["models/market-split/market_split_u3_08.fzn", "models/market-split/market_split_u3_08.scaffold.drcp"]
market_split_u3_09 = ["models/market-split/market_split_u3_09.fzn", "models/market-split/market_split_u3_09.scaffold.drcp"]
market_split_u3_10 = ["models/market-split/market_split_u3_10.fzn", "models/market-split/market_split_u3_10.scaffold.drcp"]
