rcpsp_smaller_pack033 = ["models/linear/rcpsp_smaller_pack033.fzn", "models/linear/rcpsp_smaller_pack033.scaffold.drcp"]
rcpsp_smaller_pack032 = ["models/linear/rcpsp_smaller_pack032.fzn", "models/linear/rcpsp_smaller_pack032.scaffold.drcp"]
rcpsp_smaller_pack026 = ["models/linear/rcpsp_smaller_pack026.fzn", "models/linear/rcpsp_smaller_pack026.scaffold.drcp"]
rcpsp_smaller_pack008 = ["models/linear/rcpsp_smaller_pack008.fzn", "models/linear/rcpsp_smaller_pack008.scaffold.drcp"]
rcpsp_smaller_j304_1 = ["models/linear/rcpsp_smaller_j304_1.fzn", "models/linear/rcpsp_smaller_j304_1.scaffold.drcp"]
rcpsp_smaller_j304_3 = ["models/linear/rcpsp_smaller_j304_3.fzn", "models/linear/rcpsp_smaller_j304_3.scaffold.drcp"]
rcpsp_smaller_Bl2519 = ["models/linear/rcpsp_smaller_Bl2519.fzn", "models/linear/rcpsp_smaller_Bl2519.scaffold.drcp"]
rcpsp_smaller_st103_14 = ["models/linear/rcpsp_smaller_st103_14.fzn", "models/linear/rcpsp_smaller_st103_14.scaffold.drcp"]
